apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory-oss
    targetRevision: 107.125.8        # <-- chart version
    helm:
      releaseName: artifactory-dev
      values: |
        artifactory:
          persistence:
            enabled: true
            size: 5Gi

        ingress:
          enabled: false

        postgresql:
          enabled: true
          primary:
            persistence:
              size: 5Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

